name: DiscordPAPIStats
version: ${project.version}
author: EylexLive
main: io.github.eylexlive.discordpapistats.DiscordPAPIStats
description: ${project.description}
depend: [PlaceholderAPI]
softdepend: [DiscordSRV]

commands:
  discordstats:
    aliases:
      - dcstats
      - dcpstats