name: DiscordPAPIStats
version: ${project.version}
description: ${project.description}
author: EylexLive
website: https://spigotmc.org/resources/87888
api-version: 1.13

main: io.github.eylexlive.discordpapistats.DiscordPAPIStats
depend: [PlaceholderAPI]
softdepend: [DiscordSRV]

commands:
  discordstats:
    aliases: [dcstats, dcpstats]