name: DiscordPAPIStats
version: 1.5
author: EylexLive
main: io.github.eylexlive.discordpapistats.DiscordPAPIStats
description: Show your players stats on your Discord server!
depend: [PlaceholderAPI]
softdepend: [DiscordSRV]

commands:
  discordstats:
    aliases:
      - dcstats
      - dcpstats