name: DiscordPAPIStats
version: 1.2
author: EylexLive
main: io.github.eylexlive.discordpapistats.DiscordPAPIStats
description: Show your players stats on your Discord server!
depend: [PlaceholderAPI]

commands:
  discordstats:
    aliases:
      - dcstats
      - dcpstats